import React from 'react';

function Footer() {
  return (
    <footer className="border-t-2 border-ink py-4 px-6 flex flex-col md:flex-row justify-between items-center bg-paper mt-auto">
      <h2 className="font-body font-bold tracking-widest text-sm mb-2 md:mb-0">END OF REPORT</h2>
      <span className="font-mono text-muted text-xs tracking-wider text-center md:text-right">
        GENERATED BY INGREDIENT EMBEDDING MODEL
      </span>
    </footer>
  );
}

export default Footer;
